baseurl: https://fakhrullah.github.io/moscdotmy/
languageCode: en-us
title: Malaysia Open Source Conference MOSC.my
metaDataFormat: yaml

publishDir: public
canonifyURLs: true

theme: musang
# disqusShortname: 

# Emoji is depend on theme
enableEmoji: true

# Syntax highlight
# use client-side prismjs
# or use server-side
# pygmentsCodeFences: true
# pygpygmentsuseclasses: false
# pygmentsStyle: monokai
# pygmentsCodeFencesGuessSyntax: true

# ======================================================================
#         Menu 
# ======================================================================

menu:
  home:
    - 
      name: Home
      URL: /

    -
      name: Registration
      url: /registration

    -
      name: Schedule
      url: /schedule

    -
      name: Venue
      url: /venue

    -
      name: MOSCMY Mission
      url: /mission
      
    -
      name: MOSCMY 2016
      url: /mosc-my-2016

    -
      name: Contact Us
      url: /contact-us

# ======================================================================
#         Parameters
# ======================================================================

params:
  # Sidebar description
  description: >
    The largest "Teh Tarik Session" for open source community in Malaysia

  themeOptions:
    sidebar:
      position: left
      sticky: none

  customCss: # arrays
    - css/style.css

# ======================================================================
# 
# ======================================================================

permalinks:
  blog: :year/:month/:filename

taxonomies:
  category: categories
  tag: tags
